# Generated by Django 4.0.5 on 2022-07-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineday',
            name='day',
            field=models.DateField(),
        ),
    ]
